# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0237_rename_zulip_realm_to_zulipinternal'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='realm_logo_favicon',
            field=models.BooleanField(default=False),
        ),
    ]
